# Generated by Django 2.1 on 2018-08-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxs', '0002_auto_20180829_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.NullBooleanField(),
        ),
    ]
